pitches/pitch/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class PitchForm(FlaskForm):
    category = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

class ReviewsForm(FlaskForm):
    review= TextAreaField('Write a review...', validators=[DataRequired()])
    submit = SubmitField('Submit')

pitches/main/routes.py
from flask import render_template, request, Blueprint
from pitches.models import Pitch

main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home")
def home():
    page = request.args.get('page', 1, type=int)
    pitches = Pitch.query.order_by(Pitch.date_posted.desc()).paginate(page=page, per_page=4)
    return render_template('home.html', pitches=pitches)


@main.route("/about")
def about():
    return render_template('about.html', title='About')

pitches/pitch/routes.py
from flask import (render_template, url_for, flash,
                    redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from pitches import db
from pitches.models import Pitch
from pitches.pitch.forms import PitchForm, ReviewsForm

pitchess = Blueprint('pitchess', __name__)


@pitchess.route("/pitch/new", methods=['GET', 'POST'])
@login_required
def new_pitch():
    form = PitchForm()
    if form.validate_on_submit():
        pitch = Pitch(category=form.category.data, content=form.content.data, author=current_user)
        db.session.add(pitch)
        db.session.commit()
        flash('Your pitch has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_pitch.html', title='New Pitch',
                           form=form, legend='New Pitch')


@pitchess.route('/pitch/review', methods = ['GET', 'POST'])
@login_required
def review():    
    form = ReviewsForm() 
    # reviews = Reviews.query.all()    
    if form.validate_on_submit():       
        new_review = Review(review = form.review.data)
        db.session.add(review)
        db.session.commit()
        flash('Your review has been submitted!', 'success')
        return redirect(url_for('main.review'))
    return render_template('reviews.html', form = form, title = "New Review")

@pitchess.route("/pitch/<int:pitch_id>")
def pitch(pitch_id):
    pitch = Pitch.query.get_or_404(pitch_id)
    return render_template('pitch.html', category=pitch.category, pitch=pitch)


@pitchess.route("/pitch/<int:pitch_id>/update", methods=['GET', 'POST'])
@login_required
def update_pitch(pitch_id):
    pitch = Pitch.query.get_or_404(pitch_id)
    if pitch.author != current_user:
        abort(403)
    form = PitchForm()
    if form.validate_on_submit():
        pitch.category = form.category.data
        pitch.content = form.content.data
        db.session.commit()
        flash('Your pitch has been updated!', 'success')
        return redirect(url_for('pitchess.pitch', pitch_id=pitch.id))
    elif request.method == 'GET':
        form.category.data = pitch.category
        form.content.data = pitch.content
    return render_template('create_pitch.html', title='Update Pitch',
                           form=form, legend='Update Pitch')


@pitchess.route("/pitch/<int:pitch_id>/delete", methods=['POST'])
@login_required
def delete_pitch(pitch_id):
    pitch = Pitch.query.get_or_404(pitch_id)
    if pitch.author != current_user:
        abort(403)
    db.session.delete(pitch)
    db.session.commit()
    flash('Your pitch has been deleted!', 'success')
    return redirect(url_for('main.home'))

pitches/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from pitches import db, bcrypt
from pitches.models import User, Pitch
from pitches.users.forms import (SignupForm, LoginForm, UpdateAccountForm,
                                    RequestResetForm, ResetPasswordForm)
from pitches.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route("/signup", methods=['GET', 'POST'])
def signup():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = SignupForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created!', 'success')
        return redirect(url_for('users.login'))
    return render_template('signup.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login failed', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account',
                           image_file=image_file, form=form)


@users.route("/user/<string:username>")
def user_pitches(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    pitches = Pitch.query.filter_by(author=user)\
        .order_by(Pitch.date_posted.desc())\
        .paginate(page=page, per_page=4)
    return render_template('user_pitches.html', pitches=pitches, user=user)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated!', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

pitches/templates/about.html
{% extends 'layout.html' %} {% block content %}
<h1>About Page</h1>
<p>In life, you only have 60 seconds to impress someone. 1 minute can make or break you. How do we make sure that you use your 1 minute to actually say something meaningful?</p>
{% endblock content %}

pitches/templates/account.html
{% extends 'layout.html' %} {% block content %}
<div class="content-section">
    <div class="media">
        <img class="rounded-circle account-img" src="{{ image_file }}">
        <div class="media-body">
            <h2 class="account-heading">{{ current_user.username }}</h2>
            <p class="text-secondary">{{ current_user.email }}</p>
        </div>
    </div>
    <form method="POST" action="" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Account </legend>
            <div class="form-group">
                {{ form.username.label(class = 'form-control-label') }} {% if form.username.errors %} {{ form.username(class = 'form-control form-control-lg is-invalid') }}
                <div class="invalid-feedback">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span> {% endfor %}
                </div>
                {% else %} {{ form.username(class = 'form-control form-control-lg') }} {% endif %}
            </div>
            <div class="form-group">
                {{ form.email.label(class = 'form-control-label') }} {% if form.email.errors %} {{ form.email(class = 'form-control form-control-lg is-invalid') }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span> {% endfor %}
                </div>
                {% else %} {{ form.email(class = 'form-control form-control-lg') }} {% endif %}
            </div>
            <div class="form-group">
                {{ form.picture.label() }} {{ form.picture(class="form-control-file") }} {% if form.picture.errors %} {% for error in form.picture.errors %}
                <span class="text-danger">{{ error }}</span></br>
                {% endfor %} {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class='btn btn-outline-info') }}
        </div>
    </form>
</div>
{% endblock content %}

pitches/templates/create_pitch.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{{ legend }}</legend>
                <div class="form-group">
                    {{ form.category.label(class = 'form-control-label') }}
                        {% if form.category.errors %}
                            {{ form.category(class = 'form-control form-control-lg is-invalid') }}
                            <div class="invalid-feedback">
                                {% for error in form.category.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.category(class = 'form-control form-control-lg') }}
                        {% endif %}
                </div>
                <div class="form-group">
                    {{ form.content.label(class = 'form-control-label') }}
                        {% if form.content.errors %}
                            {{ form.content(class = 'form-control form-control-lg is-invalid') }}
                            <div class="invalid-feedback">
                                {% for error in form.content.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.content(class = 'form-control form-control-lg') }}
                        {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class='btn btn-outline-info') }}
            </div>
        </form>
    </div>
{% endblock content %}

pitches/templates/home.html
{% extends 'layout.html' %} {% block content %} {% for pitch in pitches.items %}
<div class="card" style="width: 70%;text-align: center;padding: 30px;background-color: lawngreen;">
    <a href="{{ url_for( 'users.user_pitches', username=pitch.author.username) }} "><img style="border-radius: 50%;" src="{{ url_for( 'static', filename='profile_pics/' + pitch.author.image_file) }} "></a>
    <h2><a href="{{ url_for( 'pitchess.pitch', pitch_id=pitch.id) }} ">{{ pitch.category }}</a></h2>
    <p>{{ pitch.content }}</p>
    <a href="# "><button class="btn btn-info">upvote</button></a><br>
    <a href="# "><button class="btn btn-danger">downvote</button></a><br><br>
    <h6 style="font-style: italic;">Pitch uploaded by; {{ pitch.author.username }}</h5>
</div>
{% endfor %} {% for page_num in pitches.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %} {% if page_num %} {% if pitches.page == page_num %}

pitches/templates/layout.html
<!DOCTYPE html>
<html>

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    <!-- Font awesome -->
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <!-- GoogleFonts -->
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@700&display=swap" rel="stylesheet"> {% if title %}
    <title>{{ title }}</title>
    {% else %}
    <title>pitch</title>
    {% endif %}
</head>


<body style='background-color: lightgreen;'>
    <header class="site-header">
        <nav class="navbar navbar-dark bg-info" style="height: 120px; width: 57%; font-weight: bold;margin-left: 10%;background-color: lawngreen;">
            <ul class="nav">

                <li class="nav-item">
                    <a class="nav-link" href="/">Ready set pitch</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('main.home') }}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('main.about') }}">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{{ url_for('pitchess.new_pitch') }}">Pitch</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('users.account') }}">Account</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('users.logout') }}">Log out</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('users.login') }}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('users.signup') }}">sign up</a>
                </li>

            </ul>
        </nav>
    </header>
    <br>
    <main role="main" class="container">
        <div class="row">
            <div class="col-md-12">
                {% with messages = get_flashed_messages(with_categories=true) %} {% if messages %} {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                    {{ message }}
                </div>
                {% endfor %} {% endif %} {% endwith %} {% block content %}{% endblock %}
            </div>
        </div>
    </main>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html>

pitches/templates/login.html
{% extends 'layout.html' %} {% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Log in</legend>
            <div class="form-group">
                {{ form.email.label(class = 'form-control-label') }} {% if form.email.errors %} {{ form.email(class = 'form-control form-control-lg is-invalid') }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span> {% endfor %}
                </div>
                {% else %} {{ form.email(class = 'form-control form-control-lg') }} {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class = 'form-control-label') }} {% if form.password.errors %} {{ form.password(class = 'form-control form-control-lg is-invalid') }}
                <div class="invalid-feedback">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span> {% endfor %}
                </div>
                {% else %} {{ form.password(class = 'form-control form-control-lg') }} {% endif %}
            </div>
        </fieldset>
        <div class="form-check">
            {{ form.remember(class='form-check-input')}} {{ form.remember.label(class='form-check-label')}}
        </div>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
            <small class="text-muted ml-2">
                    <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                </small>
        </div>
    </form>
</div>
<div class="border-top pt-3">
    <small class="text-muted">
            Don't Have An Account? <a class="ml-2" href="{{ url_for('users.signup') }}">Sign Up Now</a>
        </small>
</div>
{% endblock content %}

pitches/templates/pitch.html
{% extends 'layout.html' %}
{% block content %}
<article class="media content-section">
    <a href="{{ url_for('users.user_pitches', username=pitch.author.username) }}"><img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + pitch.author.image_file) }}"></a>
    <div class="media-body">
      <div class="article-metadata">
        <h5 style="font-weight: 600; font-family: monospace;">By {{ pitch.author.username }}</h5>
        <i class="fa fa-calendar" aria-hidden="true"></i><small class="text-muted ml-3">{{ pitch.date_posted.strftime('%Y-%m-%d') }}</small>
        {% if pitch.author == current_user %}
            <div>
                <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('pitchess.update_pitch', pitch_id=pitch.id) }}">Update</a>
                <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
            </div>
        {% endif %}
      </div>
      <h2><a class="article-title" href="{{ url_for('pitchess.pitch', pitch_id=pitch.id) }}">{{ pitch.title }}</a></h2>
      <p class="article-content">{{ pitch.content }}</p>
    </div>
  </article>
    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">Delete Pitch?</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
            <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <form action="{{ url_for('pitchess.delete_pitch', pitch_id=pitch.id) }}" method="POST">
                <input class="btn btn-danger" type="submit" value="Delete">
            </form>
            </div>
        </div>
        </div>
    </div>
{% endblock content %}

pitches/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

pitches/templates/reset_token.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

pitches/templates/reviews.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{{ legend }}</legend>
                <div class="form-group">
                    {{ form.review.label(class = 'form-control-label') }}
                        {% if form.review.errors %}
                            {{ form.review(class = 'form-control form-control-lg is-invalid') }}
                            <div class="invalid-feedback">
                                {% for error in form.review.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.review(class = 'form-control form-control-lg') }}
                        {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class='btn btn-outline-info') }}
            </div>
        </form>
    </div>
{% endblock content %}

pitches/templates/signup.html
{% extends 'layout.html' %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                <div class="form-group">
                    {{ form.username.label(class = 'form-control-label') }}
                        {% if form.username.errors %}
                            {{ form.username(class = 'form-control form-control-lg is-invalid') }}
                            <div class="invalid-feedback">
                                {% for error in form.username.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.username(class = 'form-control form-control-lg') }}
                        {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class = 'form-control-label') }}
                        {% if form.email.errors %}
                            {{ form.email(class = 'form-control form-control-lg is-invalid') }}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.email(class = 'form-control form-control-lg') }}
                        {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class = 'form-control-label') }}
                        {% if form.password.errors %}
                            {{ form.password(class = 'form-control form-control-lg is-invalid') }}
                            <div class="invalid-feedback">
                                {% for error in form.password.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.password(class = 'form-control form-control-lg') }}
                        {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class = 'form-control-label') }}
                        {% if form.confirm_password.errors %}
                            {{ form.confirm_password(class = 'form-control form-control-lg is-invalid') }}
                            <div class="invalid-feedback">
                                {% for error in form.confirm_password.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.confirm_password(class = 'form-control form-control-lg') }}
                        {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class='btn btn-outline-info') }}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already Have An Account? <a class="ml-2" href="{{ url_for('users.login') }}">Log In</a>
        </small>
    </div>
{% endblock content %}

pitches/templates/user_pitches.html
{% extends 'layout.html' %} {% block content %}
<h1 class="mb-3">Pitches by: {{user.username }} ({{ pitches.total }})</h1>
{% for pitch in pitches.items %}
<article class="media content-section">
    <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + pitch.author.image_file) }}">
    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="{{ url_for('users.user_pitches', username=pitch.author.username) }}">{{ pitch.author.username }}</a>
            <small class="text-muted">{{ pitch.date_posted.strftime('%Y-%m-%d') }}</small>
        </div>
        <h2><a class="article-title" href="{{ url_for('pitchess.pitch', pitch_id=pitch.id) }}">{{ pitch.category }}</a></h2>
        <p class="article-content">{{ pitch.content }}</p>
    </div>
</article>
{% endfor %} {% for page_num in pitches.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %} {% if page_num %} {% if pitches.page == page_num %}
<a class="btn btn-info mb-4" href="{{ url_for('users.user_pitches', username=user.username, page=page_num) }}">{{ page_num }}</a> {% else %}
<a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_pitches', username=user.username, page=page_num) }}">{{ page_num }}</a> {% endif %} {% else %} ... {% endif %} {% endfor %} {% endblock content %}